version: "3.9"

networks:
  identity_net:
    name: identity_net

services:
  api:
    image: "identity_api:1.0.0"
    build:
      context: .
      dockerfile: "src/IdentityApi/Dockerfile"
    container_name: api
    ports:
      - "${API_PORT}:80"
    networks:
      - identity_net
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: "mssql:2022-latest"
    build:
      context: .
      dockerfile: MssqlStartup/Dockerfile
      args:
        DB_NAME: '${DB_NAME}'
        DB_USER: '${DB_USER}'
        DB_PASSWORD: '${DB_PASSWORD}'
        DB_PID: '${DB_PID}'
        DB_SA_PASSWORD: '${DB_SA_PASSWORD}'
    container_name: db
    ports:
      - "${DB_PORT}:1433"
    networks:
      - identity_net
    volumes:
      - "identity_data:/var/opt/mssql"
    env_file:
      - .env

volumes:
  identity_data:
    name: identity_data